### ISSUE TITLE
Conditional Logic Still Not Working Properly For Section Breaks & Custom HTML

### ISSUE THREAD

**Issue by ksia001** [weDevsOfficial/weforms#109]
Hello,

I'm still having an issue with the conditional logic not working properly for multiple section breaks and custom HTML. I see that the issue has been closed. Is it just that the changes have not been pushed out yet? Please advise. Thank you.

**Comment by rafsuntaskin** [comment]
Hi @ksia001 ,

The issue is resolved but yet to be released, You will get the update in next release from WordPress.org.

You may also download the [develop](https://github.com/weDevsOfficial/weforms/archive/develop.zip) version to test it out immediately.

Thanks
