### ISSUE TITLE
Not Working with Learnpress

### ISSUE THREAD

**Issue by oliverhees** [weDevsOfficial/weforms#110]
Today we have found a bug.

For a new client project we have install weforms and Learnpress.

Bevor we install Learnpress WeForms is working fine. After install Learnpress the Pages from WeForms not visible.

The WeForms Menu we can see, but the sides are all white.

I tested it with a completely new installation and only installed WeForms and Learnpress and the result was the same.

Does anyone have a solution?

**Comment by itowhid06** [comment]
Please insert this snippet in your theme's function.php file and save it.  It should solve the issue.
`add_filter( 'learn-press/admin-default-scripts', 'rt_replace_js' );

function rt_replace_js( $data ){

    $screen = get_current_screen();
    if ( $screen->base != 'toplevel_page_weforms' ) {
        return $data;
    }
    return array();
}`
