### ISSUE TITLE
Form stops working after enabling recaptcha

### ISSUE THREAD

**Issue by BrillInfotech** [weDevsOfficial/weforms#119]
I enabled recaptcha and added to form. After it start giving error 500 on submission

**Comment by rafsuntaskin** [comment]
Hi @BrillInfotech ,

Are you using any other plugin that uses reCaptcha?? Or do you have our WPUF installed?

**Comment by BrillInfotech** [comment]
I have wpuf installed with we forms. it's working fine with wpuf but not
with we forms



Thanks and Regards
Team Brill Infotech
www.brillinfotech.com

**Comment by rafsuntaskin** [comment]
This one is fixed [here](https://github.com/weDevsOfficial/weforms/commit/a7493b0480f29dc2126c51dd2992cda80224e1db) and will be released with next update.

Thanks
