### ISSUE TITLE
Only include chartjs on pages with weforms

### ISSUE THREAD

**Issue by bompus** [weDevsOfficial/weforms#122]
It appears that currently, every page of the site is including /wp-content/plugins/weforms-business/includes/libs/chartjs/chart.js

Can you update the plugin so that these dependencies are only included on the pages that actually have forms on them? Thanks!

**Comment by rafsuntaskin** [comment]
Hi @bompus ,

We already had other scripts loaded within weForms pages or short codes only. I will check on this and exclude these as well if needed. Within next update.

Thanks

**Comment by bompus** [comment]
I'm seeing the following assets now loading on front-end pages that do not have weForms on them:

/plugins/weforms-business/includes/libs/chartjs/chart.js?ver=4.9.7
/plugins/weforms/assets/wpuf/js/frontend-form.min.js?ver=1.2.9
script block with "var weforms_frontend"
script block with "var wpuf_frontend"
/plugins/weforms-business/includes/../assets/frontend-report.js?ver=4.9.7

And I think related is loading:
/wp-includes/js/jquery/ui/core.min.js?ver=1.11.4
/wp-includes/js/jquery/ui/datepicker.min.js?ver=1.11.4
/wp-includes/js/jquery/ui/widget.min.js?ver=1.11.4
/wp-includes/js/jquery/ui/mouse.min.js?ver=1.11.4
/wp-includes/js/jquery/ui/slider.min.js?ver=1.11.4

Can you verify and address in a future update? I'm running 1.2.9

**Comment by rafsuntaskin** [comment]
The new PRO update should fix this. Let us know if otherwise.

**Comment by bompus** [comment]
Looks good now. Thanks!
