### ISSUE TITLE
weForms admin section completely blank after updating to version 1.2.9

### ISSUE THREAD

**Issue by ksia001** [weDevsOfficial/weforms#125]
Hello,

Per below, I'm receiving blank screens when trying to access any of the weForms admin features after updating to version 1.2.9. Please advise. Thank you.

![weforms-1](https://user-images.githubusercontent.com/39042865/42587753-afaf065e-8509-11e8-93de-d2671d879a2e.jpg)
![weforms-2](https://user-images.githubusercontent.com/39042865/42587757-b3c117aa-8509-11e8-9047-9c4bee585f44.jpg)
![weforms-3](https://user-images.githubusercontent.com/39042865/42587760-b730aa22-8509-11e8-9c63-e3f2cff9b2ea.jpg)
![weforms-4](https://user-images.githubusercontent.com/39042865/42587766-ba8e4e72-8509-11e8-8938-c5b0f72a8dbe.jpg)
![weforms-5](https://user-images.githubusercontent.com/39042865/42587772-be310bf0-8509-11e8-815d-cf15f2363dc7.jpg)
![weforms-6](https://user-images.githubusercontent.com/39042865/42587778-c181a706-8509-11e8-9793-da5306abb9ee.jpg)
![weforms-7](https://user-images.githubusercontent.com/39042865/42587782-c485cf72-8509-11e8-9005-e0336b7dc9af.jpg)
![weforms-8](https://user-images.githubusercontent.com/39042865/42587788-c798beb8-8509-11e8-8340-6b0e7875a118.jpg)

**Comment by rafsuntaskin** [comment]
Hi, @ksia001  

We have detected this issue for users using weForms PRO 1.2.5. A new PRO version 1.2.6 has just been released please update to that version.

Thanks
