### ISSUE TITLE
weForms Pro - Personal (1.2.6) Not Allowing Changes To Be Saved For Text Block Settings, Row Settings or Column Settings When Building Pages

### ISSUE THREAD

**Issue by ksia001** [weDevsOfficial/weforms#129]
Hello,

After updating to weForms Pro - Personal (version 1.2.6), I'm no longer able to "Save Changes" for text block settings, row settings, or column settings when building pages. The issue seems to be specific to the Pro version as deactivating it (and using only the free wordpress version), allows the settings to be saved.

Also, the "remove" function is not working for "repeat field". Please advise.

Thank you

**Comment by rafsuntaskin** [comment]
Hi @ksia001,

What plugin are you using to build pages? Can you please share a ScreenShot of the console??

You may also contact our [support](https://wedevs.com/contact) so that we can take a look at your site.

Thanks

**Comment by ksia001** [comment]
I use WordPress' Bakery Page Builder to build pages. Below are some screen shots for the text block, row and column settings.
![wpb-1](https://user-images.githubusercontent.com/39042865/43008722-62208be8-8c01-11e8-8018-2e09d4f43db1.jpg)
![wpb-row](https://user-images.githubusercontent.com/39042865/43008735-692b13ae-8c01-11e8-9b4b-b2302af6dc88.jpg)
![wpb-col](https://user-images.githubusercontent.com/39042865/43008744-6e7cd4dc-8c01-11e8-9a42-e0bbc9884462.jpg)

**Comment by mahbubme** [comment]
Hello @ksia001,

There might be a [theme or plugin conflict](https://mahbub.me/how-to-identify-a-conflicting-theme-or-plugin/). Please let me know after checking.

Thanks

**Comment by ksia001** [comment]
Hi mahbubme,

I tried deactivating my plugins and even restoring my site to previous backups. However, as soon as I reactivate weForms Pro specifically (the free version seems fine), the issues return.

**Comment by rafsuntaskin** [comment]
@ksia001,

Can you please contact our [support](https://wedevs.com/contact) so that we can take a look at the errors?? 

Thanks

**Comment by mahbubme** [comment]
Hello @ksia001,

We have fixed this issue in the development version. Please wait for the next weForms pro release.

Thanks
