### ISSUE TITLE
Undefined index: recaptcha in class-ajax.php

### ISSUE THREAD

**Issue by bompus** [weDevsOfficial/weforms#133]
I'm seeing this error during submissions. I have all of my sites set up to email me whenever any error occurs, including notices, as I am a developer and it helps catch issues really quick.

Undefined index: recaptcha in /weforms/includes/class-ajax.php on line 861

Thanks!

**Comment by bompus** [comment]
Any update on this?

**Comment by mahbubme** [comment]
Hello @bompus,

We will try to reproduce this reCAPTCHA error on our side. If the error exists then we will be happy provide the fix in the next version of this plugin.

Thanks

**Comment by bompus** [comment]
@mahbubme ,

Any idea when there will be a new release to include this fix?
