### ISSUE TITLE
Label height in multi-column rows

### ISSUE THREAD

**Issue by catwings** [weDevsOfficial/weforms#139]
It would be a useful enhancement to add in a feature/option to normalize the height of the labels in a multi-column row. When one of the labels contains enough text that it is pushed to two lines, the other, shorter labels, remain on one line and the input boxes are bumped out of alignment, like in the screenshot below:

![weformscolumnlabels](https://user-images.githubusercontent.com/16243143/46803986-8139b580-cd2f-11e8-8a5b-99246ec6696b.PNG)

I tried to work around this (although not in an ideal way) by creating a custom CSS class to add a line-height's worth of padding to the shorter labels in such a row, but by only allowing one CSS class to be applied in the field info, this option has been prevented.

**Comment by mahbubme** [comment]
Hello @catwings,

You can fix it by giving a min-height of each field label. Please add the following custom CSS inside the theme's style.css and see the changes. 

`ul.wpuf-form.form-label-above li .wpuf-label {
    min-height: 65px;
}`

Thanks
