### ISSUE TITLE
Form Builder Placement Bug

### ISSUE THREAD

**Issue by catwings** [weDevsOfficial/weforms#141]
Sometimes when building a form, certain areas or fields develop a difficult-to-explain bug where their size becomes large and obscures the content behind it, as well as becoming impossible to position.  The screenshots hopefully clarify what I mean: 
![formbuilderbug1](https://user-images.githubusercontent.com/16243143/47090647-5220b980-d1f1-11e8-8dd8-bf6b487dfe2f.PNG)
![formbuilderbug2](https://user-images.githubusercontent.com/16243143/47090656-54831380-d1f1-11e8-91f8-f6dd0988825d.PNG)

In the first image, the HTML field has become enlarged, and in the second image (when the edit button for the HTML field is clicked) you can see the content behind it. This bug seems attached to the area on the page, because swapping the section divider with the HTML field just switches the bug to the section divider. I think the column classes are involved because the bug only occurs around fields that are contained within columns, and usually in conjunction with HTML fields and section dividers.

**Comment by emazharulislam** [comment]
Hello @catwings,

Could you please let me know, how can I reproduce the same scenario on local environment?

Thanks.
