### ISSUE TITLE
No submitted entries

### ISSUE THREAD

**Issue by ronoliverclarin** [weDevsOfficial/weforms#142]
I used the plugins for a week. Just today, It is my frist time to check if the entries are stored well. but the entries page are totally zero or blank page.

**Comment by mahbubme** [comment]
Hello @ronoliverclarin,

There might be a conflict with other plugin or the theme you are using. Could you please do a conflict check? Also, send us an email to support@wedevs.com with your site details, our support team will help you to fix this issue.

Thanks
