### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by lockelost** [weDevsOfficial/weforms#154]
Hi,

Whenever I create or update a form, I see thin horizontal red error box,
and here's the message.

> Failed to load plugin: code from url https://(my domain)/wp-includes/js/tinymce/plugins/code/plugin.min.js

it's just very annoying, but I didn't find any functionality failure in my usage.
PS> btw, I purchased the license.

**Comment by mahbubme** [comment]
Hello @lockelost,

Have you checked the theme or plugin conflict? If you are unable to debug the issue then contact [here](https://wedevs.com/contact/). Our support team will help you.

Thanks
