### ISSUE TITLE
weForms integration with WPERP is not working

### ISSUE THREAD

**Issue by thebengalboy** [weDevsOfficial/weforms#157]
Hello team,

The integration between weForms and WPERP seems not working. I have configured and mapped the field but when a user submits the form, it was supposed to create a CRM contact but unfortunately, it doesn't.

Would you please check?

Thanks

**Comment by mahbubme** [comment]
Hello @thebengalboy,

I am unable to reproduce the issue on my side. Please check theme or plugin conflicts. 

Reference: https://www.loom.com/share/692148d7a25b44e48d8b50d40b19c987

Thanks

**Comment by thebengalboy** [comment]
Before reporting the issue here, I have checked locally with the theme Twenty Seventeen. However, not sure why but it's working now with the latest weForms.

Thanks for your effort.
