### ISSUE TITLE
preview not available, screen blank

### ISSUE THREAD

**Issue by mkgn** [weDevsOfficial/weforms#163]
Plugin version I use : 1.4.0
Wordpress version : 4.8.3

Form editor works fine. I can create the form, save etc... Preview shows a white page. Also the page with form shortcode doesn't seem to render the form.

Seems like this is a new issue since I couldn't find a similar complain here.

**Comment by mkgn** [comment]
Some additional information. In the preview, I viewed the page source. Apart from the normal html headers etc... the WeForm content doesn't seem to be rendered properly.... It has only two lines....

        <form class="wpuf-form-add weforms-9905  wpuf-style" action="" method="post"   id="">

            <ul class="wpuf-form form-label-above">

Rest of the stuff is missing......

**Comment by shabnam611** [comment]
Hello @mkgn,

Would you mind emailing us at support@wedevs.com, so that we can help you to get the issue fixed?

Thank you for your understanding!
