### ISSUE TITLE
Unable to add the donation form from the pre-made template.

### ISSUE THREAD

**Issue by emazharulislam** [weDevsOfficial/weforms#165]
After clicking the Add Form weForms offers some pre-made template. If I choose Donation Form from the Payment Templates sections, nothing happens. I am able to click the create form button but after the click, a wheel does spins for a couple of seconds and then stopped, but the forms don't creat.

**Comment by itowhid06** [comment]
Because Donation Form has dependency on Pro version, it's not being created when weForms Pro is inactive. This Form template should have been disabled in free version.

**Comment by itowhid06** [comment]
Fixed in https://github.com/weDevsOfficial/weforms/commit/60549c9078486ad421e1e12e1c6a4a8032f0502f
