### ISSUE TITLE
Column Field Not working Properly 

### ISSUE THREAD

**Issue by cuchakma** [weDevsOfficial/weforms#182]
**Description of the bug**
The free version of **weForms(1.4.2)** has an issue with the column field.  The **column field** when used on a form, and when any fields are attached side by side using the **column field, 2 columns**. The output of the fields is not aligned side by side. Instead, the fields are shown separated from each other resulting in sequential order like a bullet list.

**How to Reproduce**
Use a column field, with 2 columns. Attach any fields on the column slots, side by side. Save it and publish it or preview it. You will notice that the fields are not aligned side by side, instead, the two fields are in sequential order which looks like a "top to down" pattern.  

**Video Evidence**
[https://www.loom.com/share/4b4ef0425ffd4848bac923d4f368f1df](url).
Copy the link and paste it on a browser separately to view the video

**Current Behaviour**
Use a **column field**, with 2 columns. Attach any fields on the column slots, side by side. Save it and publish it or preview it. You will notice that the fields are not aligned side by side, instead, the two fields are in sequential order which looks like a "top to down" pattern.  

**Expected Behaviour**
The Fields used on a **column field** should appear side by side

**Comment by rokibulislam** [comment]
this issue already solve
