### ISSUE TITLE
In Android device the data is not saving for the Signature field if it is set as required

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/weforms#186]
**Describe the bug**: 
weForms signature field is not saving the data and not letting the form submitted from the Android mobile device if the field is required.

**How to Reproduce**: 
Visit WP-admin > weForms > All forms > create a new form. Then insert a "Signature Field" and published the form through a page. Then put some signature and try to submit the form, you will catch an error message (Please fix the errors to proceed) on the browser.

**Expected behavior**: 
According to the condition applied once the canvas/signature field's data inserted it should let the form submit.

**Additional input (Screenshot/video)**: 
Please check out the video. During my testing, I found it also not working in the Chrome browser's responsive mobile mode alongside the real android device. Please check the video for better output results.

**Note**: According to the users reporting it's working fine with the iPhone device.

[A quick video](https://drive.google.com/file/d/1hpkMvwAe4JhGBhZUOEsYL5i1yb64VnUZ/view?usp=sharing)
[Screenshot from mobile](https://ibb.co/TmV9Hqm)
Feel free to let me know if you may need further information.

Thank you.

**Comment by shabnam611** [comment]
The signature field is available in the paid version of weForms.

**Comment by rokibulislam** [comment]
this issue has been fixed in pro version
