### ISSUE TITLE
HTML tag and link href is not working with the fields

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/weforms#189]
**Describe the bug**: 
If you insert any T & C fields on the weForms builder then insert any link by replacing the # then it turning all the fields into plain text on the builder. Same as the HTML tags not formating with the custom HTML field. I tested this with the latest version of weForms free (1.4.4)

**How to Reproduce**: 
Log in to your site wp-admin panel. Visit weForms -> edit your form then insert a **Terms & Condition field** on your builder then replace the # with any URL & save. Then you will find the T&C fields data will turn into plain text without link URL. Also, if you insert the **Custom HTML field** and write anything with an HTML tag it will convert the output as plain text after saving the form.

**Expected behavior**: 
The field should save the data with the URL and HTML should be formatted accordingly.

**Additional input (Screenshot/video)**: 
Please check the video for a clear output result.
[Test Video](https://drive.google.com/file/d/1iGCV72R2wwKhTph6VPx8L4KsnzcHk1Uk/view?usp=sharing)

Feel free to let me know if you may need further information.
Thank you.

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/weforms/commit/d4348f84b09a0324573faf5587a45696b36adf1d
