### ISSUE TITLE
Custom HTML field Issue

### ISSUE THREAD

**Issue by cuchakma** [weDevsOfficial/weforms#194]
**Description of the bug:**
While using the Custom HTM field, When a checkbox, radio, etc are given as input type under the HTML tag. The Checkbox, Radiobox, etc do not appear on the front end

**How to Reproduce:**
Navigate to **WP-admin panel>weForms>All Forms>select a blank form>Take a custom HTML field and insert this HTML code**  `<input type = "checkbox" name = "privacy"> <label for = "privacy"> I accept the terms and conditions on the <a href="privacy" target="_blank"> privacy policy </a> pursuant to of the GDPR (EU 2016/679) </label>`  After inserting paste the form shortcode on a page and view it on the front end. You will notice that the checkbox or any box does not appear as expected

**Evidence (Screenshot/video):**
Please paste the URL on a different browser tab [https://www.loom.com/share/0178e2d654404d2da7f42bcd4f1ee615](url)

Expected Behaviour
Checkbox used as input-type on HTML tag using custom HTML field should appear on the front end

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/weforms/commit/8de04da32410a32d5dacefbbbea621841b1f9cb1
