### ISSUE TITLE
Form Field: Linear Scale

### ISSUE THREAD

**Issue by tareq1988** [weDevsOfficial/weforms#32]
A linear field is a radio field that can be used to rate on something.
-----
![image](https://user-images.githubusercontent.com/153669/30263555-2be2ed78-96f7-11e7-8dbc-18dc70600d95.png)
-----
**Display:** 
-----
![image](https://user-images.githubusercontent.com/153669/30263578-43273c64-96f7-11e7-9c94-2b4b29eb715e.png)

**Comment by Sk-Shaikat** [comment]
https://bitbucket.org/wedevs/weforms-pro/commits/3676b46d0a87ab65008cbce233c3b3fd70fb718e
