### ISSUE TITLE
Browser autocomplete: add related tags to address field.

### ISSUE THREAD

**Issue by tareq1988** [weDevsOfficial/weforms#54]
Browsers know which form element to fill with what values. We just need to tell the browser about the correct value we are expecting.

Ref: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

**Comment by Sk-Shaikat** [comment]
https://bitbucket.org/wedevs/weforms-pro/commits/ea647d76b82c68648bb2348751d8e5dcc8bc2da3
