### ISSUE TITLE
"Please enter your weForms Pro plugin license key to get regular update and support."

### ISSUE THREAD

**Issue by Marshallsbest** [weDevsOfficial/weforms#58]
Clicking on the linked word "enter" take me to a blank page with no field available to enter my license key.

**Comment by mahbubme** [comment]
@Marshallsbest, Are you running weForms plugin on the local server? If so, license activating option for the local server is not included, it's only required for the live server.

**Comment by Marshallsbest** [comment]
nope it was installed on a managed cloud host Digital ocean

**Comment by mahbubme** [comment]
Can you create a support ticket [here](https://wedevs.com/contact/)? I will check the license issue.
