### ISSUE TITLE
Blank page on Query monitor

### ISSUE THREAD

**Issue by shivapoudel** [weDevsOfficial/weforms#76]
When a Query Monitor is installed, blank page is render on all forms when click Query monitor menu in admin bar and scrolling up to home. AND this is because query monitor also displays in this URL `http://example.io/wp-admin/admin.php?page=weforms#/qm-assets-scripts`

**Comment by mahbubme** [comment]
Hello @shivapoudel,

We are investigating this issue. I hope the fix will include in the next release of this plugin. I will keep you updated.

Thanks

**Comment by shivapoudel** [comment]
@mahbubme when is next version milestone :)

**Comment by mahbubme** [comment]
Hello @shivapoudel,

We have checked this issue on our side but failed to reproduce. Could you please create a support ticket [here](https://wedevs.com/contact/) with your site details? We will be happy to help you.

Thanks

**Comment by shivapoudel** [comment]
> Failed to reproduce.

Here it goes the screencast https://cloudup.com/cjBUvhaDPxv

**Comment by rafsuntaskin** [comment]
Hi @shivapoudel ,
This is happening due to a conflict with Vue Router and as this is not hampering any general users workflow. So, there is nothing to fix.

Thanks
