### ISSUE TITLE
Any way to support hiding / blanking the form field title

### ISSUE THREAD

**Issue by EugenMayer** [weDevsOfficial/weforms#77]
I seems like the form field title is mandatory - we would like to only have the placeholder set, but not the label for the input.

Any plans to support that ( beside using custom CSS )?

**Comment by NasirNobin** [comment]
Hey @EugenMayer,

weForms already have that feature. When editing a form, navigate to:

Settings > Display Settings > Label Position > Make it **Hidden*

http://prntscr.com/i60fpu

That should do it.

**Comment by EugenMayer** [comment]
Thank you!
