### ISSUE TITLE
1.2.6 has a broken wpackagist / composer.json package?

### ISSUE THREAD

**Issue by EugenMayer** [weDevsOfficial/weforms#87]
Pulling 1.2.6 ends in 

```
  - Installing wpackagist-plugin/weforms (1.2.6):  Checking out tags/1.2.6

                                     
  [RuntimeException]                 
  Package could not be downloaded,   
  sh: 1: svn: not found              
                            
```
while 1.2.6 works. Did you put in dev dependencies by accident?

**Comment by rafsuntaskin** [comment]
Can you please try again? 
There was an unwanted trunk folder within the tags/1.2.6 folder that might have caused the issue. We have removed that already.

Thanks

**Comment by EugenMayer** [comment]
its fixed now, thank you!
